# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Notes from the Overground
author: Rex Ledesma
email: rex.ledesma1@gmail.com
description: "Thoughts in the days"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rexledesma.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: andover
github_username: rexledesma
linkedin_username: rexledesma
twitter_username: haviddarvey

google_analytics: UA-173158493-1

permalink: /blog/:title

# Build settings
markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
plugins:
  - jekyll-minifier
  - jekyll-pandoc

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
